package compiler

import (
	"kat/ast"
	"kat/code"
	"kat/value"
)

type Compiler struct {
	instructions code.Instructions // hold generated bytecode
	constants    []value.Value     // hold constant pool
}

type Bytecode struct {
	Instructions code.Instructions
	Constants    []value.Value
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []value.Value{},
	}
}

func (c *Compiler) Compile(astNode ast.Node) error {
	switch stmt := astNode.(type) {

	case *ast.NodeProgram:
		return c.compileProgram(stmt)

	case *ast.NodeExprStmt:
		e := c.Compile(stmt.Expr)

		if e != nil {
			return e
		}

	case *ast.NodeInfixExpr:
		if e := c.Compile(stmt.Left); e != nil {
			return e
		}

		if e := c.Compile(stmt.Right); e != nil {
			return e
		}

	case *ast.NodeInteger:
		val := &value.Int{Value: stmt.Value}
		c.emit(code.OpConstant, c.addConstant(val))
	}

	return nil
}

func (c *Compiler) addConstant(val value.Value) int {
	c.constants = append(c.constants, val)
	return len(c.constants) - 1
}

func (c *Compiler) emit(opCode code.Opcode, operands ...int) int {
	instruction := code.Make(opCode, operands...)
	return c.addInstruction(instruction)
}

func (c *Compiler) addInstruction(instruction []byte) int {
	posOfNewInstruction := len(c.instructions)
	c.instructions = append(c.instructions, instruction...)
	return posOfNewInstruction
}

func (c *Compiler) compileProgram(node *ast.NodeProgram) error {
	for _, stmt := range node.Body {
		e := c.Compile(stmt)

		if e != nil {
			return e
		}
	}

	return nil
}

func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}
