package compiler

import (
	"kat/ast"
	"kat/code"
	"kat/value"
)

type Compiler struct {
	instructions code.Instructions // hold generated bytecode
	constants    []value.Value     // hold constant pool
}

type Bytecode struct {
	Instructions code.Instructions
	Constants    []value.Value
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []value.Value{},
	}
}

func (c *Compiler) Compile(astNode ast.Node) error {
	switch stmt := astNode.(type) {

	case *ast.NodeProgram:
		return c.compileProgram(stmt)

	case *ast.NodeExprStmt:
		e := c.Compile(stmt.Expr)

		if e != nil {
			return e
		}

	case *ast.NodeInfixExpr:

	}

	return nil
}

func (c *Compiler) compileProgram(node *ast.NodeProgram) error {
	for _, stmt := range node.Body {
		e := c.Compile(stmt)

		if e != nil {
			return e
		}
	}

	return nil

}

func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}
