package compiler

import (
	"fmt"
	"kat/ast"
	"kat/code"
	"kat/value"
)

type Compiler struct {
	instructions code.Instructions // hold generated bytecode
	constants    []value.Value     // hold constant pool
}

type Bytecode struct {
	Instructions code.Instructions
	Constants    []value.Value
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []value.Value{},
	}
}

func (c *Compiler) Compile(astNode ast.Node) error {
	switch stmt := astNode.(type) {

	case *ast.NodeProgram:
		return c.compileProgram(stmt)

	case *ast.NodeExprStmt:
		e := c.Compile(stmt.Expr)

		if e != nil {
			return e
		}

		c.emit(code.OpPop)

	case *ast.NodeInfixExpr:
		if e := c.Compile(stmt.Left); e != nil {
			return e
		}

		if e := c.Compile(stmt.Right); e != nil {
			return e
		}

		switch stmt.Operator {
		case "+":
			c.emit(code.OpAdd)

		case "-":
			c.emit(code.OpSub)

		case "*":
			c.emit(code.OpMul)

		case "/":
			c.emit(code.OpDiv)

		case ">":
			c.emit(code.OpGreaterThan)

		case "<":
			c.emit(code.OpLessThan)

		case "==":
			c.emit(code.OpEqual)

		case "!=":
			c.emit(code.OpNotEqual)

		default:
			return fmt.Errorf("unknown operator: %s", stmt.Operator)
		}

	case *ast.NodeInteger:
		val := &value.Int{Value: stmt.Value}
		c.emit(code.OpConstant, c.addConstant(val))

	case *ast.NodeBoolean:
		if stmt.Value {
			c.emit(code.OpTrue)
		} else {
			c.emit(code.OpFalse)
		}

	case *ast.NodePrefixExpr:
		if err := c.Compile(stmt.Right); err != nil {
			return err
		}

		switch stmt.Operator {
		case "-":
			c.emit(code.OpMinus)
		case "!":
			c.emit(code.OpBang)
		default:
			return fmt.Errorf("Unknow operator %s", stmt.Operator)
		}
	}

	return nil
}

func (c *Compiler) addConstant(val value.Value) int {
	c.constants = append(c.constants, val)
	return len(c.constants) - 1
}

func (c *Compiler) emit(opCode code.Opcode, operands ...int) int {
	instruction := code.Make(opCode, operands...)
	return c.addInstruction(instruction)
}

func (c *Compiler) addInstruction(instruction []byte) int {
	posOfNewInstruction := len(c.instructions)
	c.instructions = append(c.instructions, instruction...)
	return posOfNewInstruction
}

func (c *Compiler) compileProgram(node *ast.NodeProgram) error {
	for _, stmt := range node.Body {
		e := c.Compile(stmt)

		if e != nil {
			return e
		}
	}

	return nil
}

func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}
